# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7993185cae546372f990673bd3d26feda135faebe15585afc2ecfe932fd8d385d33389bb69bfac71069204b1e2b8481bee27e65c090e477d37e84e323c3fe5d5

test:
  secret_key_base: 31c938a45c2bb081a8ae24cdbe3467d3e5c69203d0db653ec6064a1e682fece27552eddd443d2e9a02dedbf7d01b9162ac14887430b35a909103b645e36e9620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
